# [START cloudrun_rails_cloudbuild]
steps:
  - id: "build image"
    name: "${_GCR_HOSTNAME}/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -t ${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME} . ",
      ]

  - id: "push image"
    name: "${_GCR_HOSTNAME}/cloud-builders/docker"
    args: ["push", "${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "apply migrations"
    name: "${_GCR_HOSTNAME}/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      [
        "-c",
        "/buildstep/execute.sh -i ${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME} -- bundle exec rails db:migrate",
      ]

substitutions:
  _REGION: europe-west3
  _SERVICE_NAME: next_test_service
  _INSTANCE_NAME: next_test_instance
  _SECRET_NAME: rails-master-key
  _GCR_HOSTNAME: eu.gcr.io

images:
  - "${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}"
# [END cloudrun_rails_cloudbuild]
